---
title: "2021 List of Homework"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
## week 2
github <- list(
  title = "GitHub",
  topics = c("Creating a new project"),
  pdf = "",
  rmd = "homework/week_01/hw_01_github_remotes.Rmd",
  html = "homework/week_01/hw_01_github_remotes.html",
  data = "homework/week_01/palmer_penguins.csv",
  key = ""
)

## week 3
forking_workflows <- list(
  title = "Forking workflows",
  topics = c("Forking workflows"),
  pdf = "",
  rmd = "homework/week_02/hw_02_forking_workflow.Rmd",
  html = "homework/week_02/hw_02_forking_workflow.html",
  data = "",
  key = ""
)

## week 4
data_cleaning <- list(
  title = "Cleaning data",
  topics = c("Cleaning data"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)

## week 5
databases <- list(
  title = "Databases",
  topics = c("Relational databases"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)

## week 6
data_viz <- list(
  title = "Data visualization",
  topics = c("Data visualization"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)

## week 7
packages <- list(
  title = "R packages",
  topics = c("Building R packages"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)

## week 8
markdown <- list(
  title = "R Markdown",
  topics = c("Applications of R Markdown"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)

## week 9
shiny_apps <- list(
  title = "Shiny apps",
  topics = c("Shiny apps"),
  pdf = "",
  rmd = "",
  html = "",
  data = "",
  key = ""
)
```

