---
title: "Metadata"
subtitle: "Intro to Environmental Data Science<br>FISH 497A"
author: "Mark Scheuerell"
date: "10 February 2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center", out.width = '90%')
```

## Goals for today

* Understand the concept of *metadata*

> - Understand the different kinds of metadata

> - Get an introduction to the *Ecological Metadata Language*


## What is metadata? | Definition

"data that provides information about other data"


## What is metadata? | Definition

a shorthand representation of the data to which they refer


## Metadata is everywhere | Book

* title  
* author  
* publisher  
* copyright  
* table of contents / index  


## Metadata is everywhere | Phone calls

* number called or received from  
* time initiated & ended  
* location of callers  


## Metadata is everywhere | Email

* subject  
* from  
* to  
* date & time sent  
* sending & receiving IP addresses  


## Kinds of metadata | Descriptive

Descriptive metadata is descriptive information about a resource. It is used for discovery and identification. It includes elements such as title, abstract, author, and keywords.


## Kinds of metadata | Structural

Structural metadata is metadata about containers of data and indicates how compound objects are put together, for example, how pages are ordered to form chapters. It describes the types, versions, relationships and other characteristics of digital materials.


## Kinds of metadata | Administrative

Administrative metadata is information to help manage a resource, like resource type, permissions, and when and how it was created.


## Kinds of metadata | Reference

Reference metadata is information about the contents and quality of statistical data.


## Kinds of metadata | Statistical

Statistical metadata, also called process data, may describe processes that collect, process, or produce statistical data
