---
title: "Metadata"
subtitle: "Intro to Environmental Data Science<br>FISH 497A"
author: "Mark Scheuerell"
date: "10 February 2021"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center", out.width = '90%')
```

## Goals for today

* Understand the concept of *metadata*

> - Understand the different kinds of metadata

> - Get an introduction to the *Ecological Metadata Language*


## What is metadata? | Definition

"data that provides information about other data"


## What is metadata? | Definition

"shorthand representation of the data to which they refer"


## Metadata is everywhere | Book

* title  
* author  
* publisher  
* copyright  
* table of contents / index  


## Metadata is everywhere | Phone calls

* number called or received from  
* time initiated & ended  
* location of callers  


## Metadata is everywhere | Email

* subject  
* from  
* to  
* date & time sent  
* sending & receiving IP addresses  


## Benefits of metadata

Metadata benefits science by

1) increased data longevity

    > - long-term studies outlast investigators/students
    
    > - many scientists contribute info from many areas


## Benefits of metadata

Metadata benefits science by

1) increased data longevity

2) increased data reuse & sharing 

    > - info helps others know if/how they could them
    
    > - facilitates meta-analyses


## Benefits of metadata

Metadata benefits science by

1) increased data longevity

2) increased data reuse & sharing 

3) expanded scales/scopes of analyses

    > - short-term evolve into long-term
    
    > - facilitates creativity


## Kinds of metadata | Descriptive

*Descriptive metadata* is information about a resource that is used for searching & identification

> - title  
> - abstract  
> - author  
> - keywords


## Kinds of metadata | Structural

*Structural metadata* indicates how 2+ objects are connected

> - tables    
> - fields 
> - keys  
> - relationships  


## Entity–relationship model

Structural metadata are often conceptualized in an *entity–relationship model* 


## Entity–relationship model | Entity

An *entity* can be physical or logical

> - physical entities *actually* exist (eg, lake, fish)

> - logical entities *could* exist (eg, a sampling event)

> - entities have attributes (eg, depth, mass, date)


## Entity–relationship model | Relationship

Entities are connected via a *relationship*

> - relationships can be thought of as verbs

> - Sarah *supervises* Mark

> - Omar *samples* Lake Washington


## Entity–relationship diagram

ER models are usually drawn as boxes (entities) connected by lines (relationships)


## Entity–relationship diagram{data-background=images/ER_model_1.png data-background-size=90%}


## Entity–relationship diagram{data-background=images/ER_model_2.png data-background-size=90%}


## Kinds of metadata | Administrative

Administrative metadata refers to technical info about a data file

> - file type (eg, `.csv`)  
> - when the file was created
> - how the file was created


## Administrative metadata | Rights management

> - Who has had custody/ownership of the data?  
> - What intellectual property rights must be observed?


## Administrative metadata | Preservation

> - Where are the data stored?  
> - How are they identified (eg, digitial object identifier)?  


## Kinds of metadata | Reference

Information about the contents and quality of statistical data

> - description of fields  
> - QA/QC


## Kinds of metadata | Process

Describes the collection and any processing of the data

> - raw vs cleaned
> - reproducible workflows


## Process metadata | Michener (2005){data-background=images/eco_metadata.png data-background-position="50% 60%" data-background-size=90%}


## Kinds of metadata | Accessibility

Information about improved access to data

> - audio transcripts  
> - alternate text for an image  
> - large print


## Section 508{data-background=images/section508.png data-background-position="50% 60%" data-background-size=70%}


## How much metadata is enough?

Two factors to consider

1) effort involved in creating the metadata

2) value derived from it

In general, assume that "more is better"


## No metadata{data-background=images/metadata_ex1.png data-background-position="50% 40%" data-background-size=90%} 


## Minimal metadata{data-background=images/metadata_ex2.png data-background-position="50% 40%" data-background-size=90%} 


## Extensive{data-background=images/metadata_ex3.png data-background-position="70% 50%" data-background-size=50%} 


# Ecological Metadata Language


## Ecological Metadata Language

EML describes a range of essential aspects of ecological data

> - names & definitions of variables  
> - units of measurement  
> - date/time/location of data collection  
> - identity/contact for individual who collected the data  
> - sampling design


## Ecological Metadata Language

EML reduces ambiguity & uncertainty by formalizing metadata concepts

> - uses comprehensive **and** standardized set of terms  
> - uses definitions intended specifically for ecological data

