---
title: "Course overview"
subtitle: "Intro to Environmental Data Science<br>FISH 497A"
author: "Mark Scheuerell"
date: "4 January 2021"
output:
  ioslides_presentation:
    css: lecture_slides.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## {.flexbox .vcenter .bigger}

<font size="10">
WHO AM I? 
</font>


## Mark Scheuerell

* Asst Unit Leader, USGS WACFWRU

* Assoc Professor, School of Aquatic and Fishery Sciences


## My role as course instructor

> - Help you learn the material

> - Help you learn how to ask for help

> - Be a future resource


## My role as course instructor

> - I plan to fail

> - A lot

> - In public


## {.flexbox .vcenter .bigger}

<font size="10">
WHO ARE YOU? 
</font>


## Introduce yourself via Zoom chat:

1. Your degree program (undergrad, grad)

2. Your school/department

3. Your major (undergrads) or area of study (grads)

<br>

For example,  

`undergrad, SEFS, ESRM`  

`grad, SAFS, salmon migration timing`


## Things we'll emphasize

* Thinking about data separately from research

> - Increasing efficiency & reproducibility

> - Facilitating collaboration with others

> - Finding answers from the community

> - Communicating our workflows & results


## Things we won't emphasize

* Specific options for cleaning & tidying data (eg, tidyverse)

> - Specific analytical techniques (eg, machine learning)

> - Specific plotting techniques (eg, ggplot)


## How are we going to do this?

* Use *lots* of online resources

* Use open/live coding

* Rely on our community for help


## {.flexbox .vcenter .bigger}

<font size="10">
What is *data science*? 
</font>



## {.flexbox .vcenter .bigger}

<font size="10">
[__Course information__](https://fish497.github.io/website)
</font>

