---
title: "Creating an expository figure"
subtitle: "Assignment #5"
author: "FISH 497 - Intro to Environmental Data Science"
date: "12 February 2021"
output:
  html_document:
    theme: readable
    highlight: textmate
    toc: false
    toc_float: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<br>

# Background

This week we learned about some graphic design principles, which included an example of creating an *expository* figure from an initial *exploratory* figure. Your assignment this week is to use the provided dataset to 

1) begin by creating an *exploratory* figure you'd like about *any* aspect of the data, and  

2) create an *expository* figure that builds upon your original figure.

Your figure can include some aspect of data anlysis (eg, linear regression), but there is no requirement for you to do so. You can use either **base graphics** or **ggplot2** to complete this assignment. 


***

# Data description

The data come from the [{FSAdata}](https://github.com/droglenc/FSAdata) package, which was created by [Derek Ogle](https://derekogle.com/) as part of his book [*Introductory Fisheries Analysis with R*](http://derekogle.com/IFAR/). The dataset contains information on the ages (subsample), and length and mass (all fish) for male and female Siscowet Lake Trout captured at four locations in Michigan waters of Lake Superior.

## Format

A data frame with 780 observations on the following 8 variables.

1) `locID`: Locations (`Blind Sucker`, `Deer Park`, `Grand Marais`, `Little Lake Harbor`) 

2) `pnldep`: Depth of gillnet panel in which the fish was captured  

3) `mesh`: Gillnet stretch mesh measure  

4) `fishID`: Unique fish identification code  

5) `sex`: Sex (`F` = female; `M` = male)  

6) `age`: Assigned ages (years)  

7) `len`: Total length (mm)  

8) `wgt`: Weight (g)  


***

# Using R Markdown

You are welcome to use **R Markdown** to complete this assignment, but if you'd rather not, I will also happily accept a combination of a `.R` script with your plotting code and a saved version of your figure in a format such as `.png`, `.jpg`, or `.pdf`. Click [here](../../lectures/week_07/intro_rmarkdown.html) for an introduction to **R Markdown**.

