---
title: "Getting help from others"
author: "Mark Scheuerell"
date: "27 January 2021"
output:
  html_document:
    theme: readable
    highlight: textmate
    toc: true
    toc_float: true
    toc_depth: 3
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.align = "center", out.width = '90%')
```

<br>

# Motivation

There is a good chance the you've already had to ask someone for help with a question related to some aspect of data science. For example, 

* What does this error mean?

* Why can I not reproduce what you've done?

* How do I [fill in the blank]?

* Is there an existing package that allows me to [fill in the blank]?

The bad news is that these types of questions may follow you around throughout your career. The good news, however, is that there is a large community of people willing to help you find the solutions you need.

***

# Minimal, reproducible example

When you get stuck on a problem and need some advice, others will be able to better provide assistance if you include code that 

1. they can easily understand, and

2. they can use to reproduce the problem.

This process is variously referred to as creating a

* minimal, **rep**roducible **ex**ample (reprex)

* **m**inimal, **c**omplete and **v**erifiable **e**xample (mcve)

* **m**inimal, **w**orkable **e**xample (mwe)

The bottom line is that you should

* use the least amount of code possible to produce the problem (minimal)

* provide *everything* (code, data) someone would need to reproduce your problem (complete)

* verify that the code you're about to share reproduces the problem (reproducible)

In addition, you should phrase your question in manner that is polite and free of jargon or other language constructs that might confuse people. The data science community is global, so recognize that someone reading your question might not speak English as a first language. Also consider that others may very well stumble across your question and, hopefully, the correct answer years after it was solved. As such, using plain, descriptive language in the title and body of a post will allows to find it when searching for answers. For example, [this problem](https://stackoverflow.com/questions/36634641/formatting-table-headings-in-rmarkdown) I posted on Stack Overflow in 2016 has since received over 1000 views!

## Minimal

There tends to be a strong negative correlation between the length of your code and the likelihood someone will 1) read all the way through it, and 2) actually solve your problem. Therefore, you should streamline your example along the following lines of advice.

* Consider creating a new script, including *only those elements germane to the problem* 

* Remove extraneous information that doesn't influence the problematic code

* Use simple, descriptive names for parameters, variables, and functions

* Include meaningful comments in your code to help others understand what you're trying to accomplish

* Take advantage of your IDE's options to create nicely formatted code (e.g., uses spaces--not tabs--for indents; in **RStudio** use `command+I` on a Mac or `ctrl+I` in Windows)

## Complete

Make sure all information necessary to reproduce the problem is included in the question itself:

If the problem requires some server-side code as well as some XML-based configuration, include code for both. If a web page problem requires HTML, some JavaScript, and a stylesheet, include code for all three. The problem might not be in the code that you think it is in.

Use individual code blocks for each file or snippet you include. Provide a description for the purpose of each block.

Use Stack Snippets to include runnable HTML, JavaScript, or CSS.

DO NOT use images of code. Copy the actual text from your code editor, paste it into the question, then format it as code. This helps others more easily read and test your code.

## Reproducible

To help you solve your problem, others will need to verify that it exists:

Describe the problem. "It doesn't work" isn't descriptive enough to help people understand your problem. Instead, tell other readers what the expected behavior should be. Tell other readers what the exact wording of the error message is, and which line of code is producing it. Use a brief but descriptive summary of your problem as the title of your question.

Eliminate any issues that aren't relevant to the problem. If your question isn’t about a compiler error, ensure that there are no compile-time errors. Use a program such as JSLint to validate interpreted languages. Validate any HTML or XML.

Double-check that your example reproduces the problem! If you inadvertently fixed the problem while composing the example but didn't test it again, you'd want to know that before asking someone else to help.

It might help to shut the system down and restart it, or transport the example to a fresh environment to confirm it really does provide an example of the problem.

***

# The `reprex` package



